---
# Source: grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: grafana
  namespace: apm
  labels:
    app: grafana
    chart: grafana-4.4.0
    heritage: Helm
    release: grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: apm
roleRef:
  kind: Role
  name: grafana
  apiGroup: rbac.authorization.k8s.io
