---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: apm
  labels:
    app: grafana
    chart: grafana-4.4.0
    release: grafana
    heritage: Helm
type: Opaque
data:
  admin-user: "xxx"
  admin-password: "xxx="
  ldap-toml: ""
